# Generated by Django 5.1.6 on 2025-02-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('America/New_York', 'America/New_York'), ('Europe/London', 'Europe/London'), ('Asia/Dhaka', 'Asia/Dhaka'), ('Asia/Tokyo', 'Asia/Tokyo'), ('Australia/Sydney', 'Australia/Sydney')], default='UTC', max_length=50),
        ),
    ]
