# Generated by Django 5.1.6 on 2025-03-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0002_alter_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC')], default='UTC', max_length=50),
        ),
    ]
