# Generated by Django 5.1.5 on 2025-03-17 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0005_user_account_locked_until_user_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'This username is already taken.'}, help_text='150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username.', regex='^[\\w.@+-]+\\Z')], verbose_name='username'),
        ),
    ]
