checksumBehavior: 'update'
enableGlobalCache: false
nodeLinker: 'pnp'
yarnPath: '.yarn/releases/yarn-4.6.0.cjs'
npmRegistryServer: 'https://registry.npmjs.org/'
packageExtensions:
  'typescript@*':
    dependencies:
      '@types/node': '*'
      '@types/jest': '*'
      '@types/react': '*'
      '@types/react-dom': '*'
