x-env-config: &env-config
  env_file:
    - ${ENV_FILE:-.env}

x-resource-limits: &resource-limits
  deploy:
    resources:
      limits:
        cpus: '0.50'
        memory: 512M
      reservations:
        memory: 128M

x-logging: &logging-config
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

x-security-opts: &security-opts
  security_opt:
    - no-new-privileges:true
  cap_drop:
    - ALL

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: DjangoAllauth_postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"  # Only bind to localhost for security
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      DjangoAllauth_network:
        aliases:
          - database
          - postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    <<: [*env-config]

  nginx:
    build:
      context: ./nginx 
      dockerfile: Dockerfile
    container_name: DjangoAllauth_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
    environment:
      - SSL_CERT=/etc/nginx/ssl/nginx-selfsigned.crt
      - SSL_KEY=/etc/nginx/ssl/nginx-selfsigned.key
      - BACKEND_PORT=8000  # Add this for variable substitution
      - FRONTEND_HOST=frontend  # Add this for variable substitution
    user: root  # Override USER directive from Dockerfile for development
    networks:
      - DjangoAllauth_network
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    <<: [*resource-limits, *logging-config, *security-opts, *env-config]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    container_name: DjangoAllauth_backend
    restart: unless-stopped
    volumes:
      - ${DEVELOPMENT_MODE:+./backend:/app} # Mount volume only in development mode
      - static_volume:/app/collected_static
      - media_volume:/app/media
      - logs_volume:/app/logs
      - ./backend/templates:/app/templates
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    ports:
      - "127.0.0.1:${BACKEND_PORT}:8000" # Use BACKEND_PORT from .env or default to 8000, bind to localhost only
    networks:
      DjangoAllauth_network:
        aliases:
          - backend
    depends_on:
      postgres:
        condition: service_healthy
      nginx:
        condition: service_healthy
    entrypoint: ["/app/entrypoint.sh"]
    command: [
      "gunicorn",
      "--timeout=120",
      "-b", "0.0.0.0:8000",
      "core.wsgi:application"
    ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthcheck/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Give more time for startup
    <<: [*resource-limits, *logging-config, *env-config]

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
      target: ${NODE_ENV:-development}
    container_name: DjangoAllauth_frontend
    restart: unless-stopped
    volumes:
      - ${DEVELOPMENT_MODE:+./frontend:/app}  # Only mount in development mode
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    ports:
      - "127.0.0.1:3000:3000"  # Only bind to localhost for security
    networks:
      - DjangoAllauth_network
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - backend
    <<: [*resource-limits, *logging-config, *env-config, *security-opts]

networks:
  DjangoAllauth_network:
    driver: bridge
    name: DjangoAllauth_network
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

volumes:
  postgres_data:
    name: DjangoAllauth_postgres_data
  static_volume:
    name: DjangoAllauth_static_volume
  media_volume:
    name: DjangoAllauth_media_volume
  node_modules:
    name: DjangoAllauth_node_modules
  next_cache:
    name: DjangoAllauth_next_cache
  logs_volume:
    name: DjangoAllauth_log_volume
  nginx_logs_volume:
    name: DjangoAllauth_nginx_logs_volume
